#!/usr/bin/env bash
# 1906-flag-engine-mismatched-docs.sh -- Issue #1906: the codex AGENTS.md
# doc-backfill sweep must DETECT + FLAG (never delete) an EXISTING
# engine-mismatched instruction doc.
#
# #1896 made the sweep fail-closed on the roster engine so a new spurious codex
# AGENTS.md is no longer scaffolded onto a claude agent GOING FORWARD. But #1896
# only blocks NEW mis-scaffold — it does not surface engine-mismatched docs that
# ALREADY exist on installs that ran a pre-fix version. cm-prod's
# `cosmax_sales_mdj` is a correct `claude` agent (authoritative CLAUDE.md
# present) that ALSO carries a stale Codex-contract AGENTS.md (6 KB, "You are a
# Codex (gpt) agent ... runtime: Codex CLI") left by a pre-#1896 mis-scaffold.
#
# The residue is invisible to the sweep: `detect_engine` keys on CLAUDE.md only,
# so a stray codex AGENTS.md never flips the decision off `skip` and the file is
# never inspected. #1906 adds a REPORT-ONLY residue detector that flags it.
#
#   T1  claude-roster agent carrying a Codex-contract AGENTS.md alongside a
#       correct CLAUDE.md -> appears in `engine_mismatch_docs`, non-clean=1, the
#       [hygiene] task body names it, and the file is UNTOUCHED (byte-identical,
#       no backup created). REPORT-ONLY: nothing deleted/renamed/edited.
#   T2  correct claude agent with only CLAUDE.md (no AGENTS.md) -> NOT flagged,
#       clean pass (non-clean=0, no spurious task).
#   T3  NEGATIVE CONTROL: a genuine codex-roster agent with its own codex
#       AGENTS.md is NOT a mismatch -> never appears in engine_mismatch_docs.
#
# Pure-python CLI surfaces (backfill-codex-entrypoints + daemon-helpers) driven
# against a temp BRIDGE_HOME — the operator's live tree is never touched and the
# test runs identically on macOS and Linux. No heredoc-stdin / `<<<` / `< <()`
# procsub / `| grep -q` (lint-heredoc-ban H3 + #1813 SIGPIPE): printf-built
# fixtures, `python3 -c`, pure-bash `[[ == ]]`.

set -euo pipefail

SMOKE_NAME="1906-flag-engine-mismatched-docs"
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=scripts/smoke/lib.sh
source "$SCRIPT_DIR/lib.sh"

REPO_ROOT="$SMOKE_REPO_ROOT"

cleanup() {
  smoke_cleanup_temp_root
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

setup_bridge_fixture() {
  smoke_cleanup_temp_root
  smoke_setup_bridge_home "$SMOKE_NAME"
  export BRIDGE_DATA_ROOT="$BRIDGE_HOME/data"
  export BRIDGE_AGENT_ROOT_V2="$BRIDGE_DATA_ROOT/agents"
  {
    printf '%s\n' 'BRIDGE_LAYOUT=v2'
    printf 'BRIDGE_DATA_ROOT=%q\n' "$BRIDGE_DATA_ROOT"
  } >"$BRIDGE_STATE_DIR/layout-marker.sh"
  mkdir -p "$BRIDGE_AGENT_ROOT_V2"
}

# A single-agent roster with an explicit engine declaration.
write_roster() {
  local agent="$1"
  local engine="$2"
  {
    printf 'BRIDGE_AGENT_IDS=("%s")\n' "$agent"
    printf 'BRIDGE_AGENT_CLASS["%s"]="user"\n' "$agent"
    printf 'BRIDGE_AGENT_ENGINE["%s"]="%s"\n' "$agent" "$engine"
    printf 'BRIDGE_AGENT_SESSION["%s"]="agb-%s"\n' "$agent" "$agent"
    printf 'BRIDGE_AGENT_SOURCE["%s"]="static"\n' "$agent"
    printf 'BRIDGE_AGENT_WORKDIR["%s"]="%s"\n' "$agent" "$BRIDGE_AGENT_ROOT_V2/$agent/workdir"
  } >"$BRIDGE_ROSTER_FILE"
}

# Write a stale Codex-contract AGENTS.md (the residue) at the given path. The
# identity line is the exact prose the codex AGENTS.md template materializes
# (CODEX_CONTRACT_AGENTS_MD_MARKER), so the content-signature detector flags it.
write_codex_contract_agents_md() {
  local dst="$1"
  {
    printf '%s\n' '<!-- Managed by agent-bridge. Regenerated by agent-bridge. -->'
    printf '%s\n\n' '# Agent — Role'
    printf '%s\n' '<!-- BEGIN AGENT BRIDGE DOC MIGRATION -->'
    printf '%s\n' 'You are a Codex (gpt) agent running inside Agent Bridge. This file is your'
    printf '%s\n\n' 'operating contract. Read it top to bottom.'
    printf '%s\n' 'Your runtime: Codex CLI.'
    printf '%s\n' '<!-- END AGENT BRIDGE DOC MIGRATION -->'
  } >"$dst"
}

# A correct claude profile: authoritative CLAUDE.md, no codex heuristic trip.
write_clean_claude_profile() {
  local agent="$1"
  local profile="$BRIDGE_AGENT_HOME_ROOT/$agent"
  local workdir="$BRIDGE_AGENT_ROOT_V2/$agent/workdir"
  mkdir -p "$profile" "$workdir"
  printf '# %s — Monitor (런타임: Claude Code CLI)\n' "$agent" >"$profile/CLAUDE.md"
  printf '# soul\n' >"$profile/SOUL.md"
}

# A genuine codex profile home with its own codex AGENTS.md (negative control).
write_codex_profile_with_agents_md() {
  local agent="$1"
  local profile="$BRIDGE_AGENT_HOME_ROOT/$agent"
  local workdir="$BRIDGE_AGENT_ROOT_V2/$agent/workdir"
  mkdir -p "$profile" "$workdir"
  printf '# Session Type\n\n- Session Type: static-codex\n- Engine: codex\n' >"$profile/SESSION-TYPE.md"
  printf '# %s — Monitor (런타임: Codex CLI)\n' "$agent" >"$profile/CLAUDE.md"
  printf '# soul\n' >"$profile/SOUL.md"
  write_codex_contract_agents_md "$profile/AGENTS.md"
}

run_backfill() {
  local agent="$1"
  python3 "$REPO_ROOT/bridge-upgrade.py" backfill-codex-entrypoints \
    --source-root "$REPO_ROOT" --target-root "$BRIDGE_HOME" --admin-agent "$agent" 2>/dev/null
}

non_clean_of() {
  python3 "$REPO_ROOT/bridge-daemon-helpers.py" agent-doc-backfill-non-clean "$1"
}

json_field() {
  # json_field <file> <key> -> prints the JSON value (count fields).
  python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get(sys.argv[2], ""))' "$1" "$2"
}

# Stable digest of a file's bytes (for the untouched assertion). Uses python3
# so no `<<<` / pipe is needed and it is portable macOS/Linux.
file_digest() {
  python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest())' "$1"
}

# ===========================================================================
# T1 — claude-roster agent with a stale Codex-contract AGENTS.md: FLAGGED in
#      engine_mismatch_docs, non-clean=1, task body names it, file UNTOUCHED.
# ===========================================================================
test_stale_codex_agents_md_is_flagged_not_removed() {
  setup_bridge_fixture
  local agent=cosmax_sales_mdj
  write_roster "$agent" claude
  write_clean_claude_profile "$agent"
  local profile="$BRIDGE_AGENT_HOME_ROOT/$agent"
  write_codex_contract_agents_md "$profile/AGENTS.md"

  local before_digest=""
  before_digest="$(file_digest "$profile/AGENTS.md")"

  local summary=""
  summary="$(run_backfill "$agent")"
  printf '%s' "$summary" >"$SMOKE_TMP_ROOT/t1.json"

  # Flagged in the report list, naming the agent + the codex contract.
  smoke_assert_contains "$summary" "\"engine_mismatch_docs\"" \
    "T1: summary missing the engine_mismatch_docs list"
  smoke_assert_contains "$summary" "$agent" \
    "T1: engine_mismatch_docs did not name the claude agent"
  smoke_assert_contains "$summary" "\"detected_contract\": \"codex\"" \
    "T1: engine_mismatch_docs did not record the codex contract"
  smoke_assert_eq "1" "$(json_field "$SMOKE_TMP_ROOT/t1.json" engine_mismatch_docs_count)" \
    "T1: expected exactly one engine-mismatched doc"

  # Non-clean so the operator gets the [hygiene] warning task.
  smoke_assert_eq "1" "$(non_clean_of "$SMOKE_TMP_ROOT/t1.json")" \
    "T1: a flagged engine-mismatched doc was not reported non-clean (operator would never see it)"

  # REPORT-ONLY: the stray AGENTS.md is byte-identical and no backup was created.
  smoke_assert_file_exists "$profile/AGENTS.md" \
    "T1: the flagged AGENTS.md was removed (must be report-only)"
  smoke_assert_eq "$before_digest" "$(file_digest "$profile/AGENTS.md")" \
    "T1: the flagged AGENTS.md was modified (must be byte-identical, report-only)"
  local stray_count=""
  stray_count="$(python3 -c 'import glob,sys; print(len(glob.glob(sys.argv[1]+"/AGENTS.md.*")))' "$profile")"
  smoke_assert_eq "0" "$stray_count" \
    "T1: a backup/rename of AGENTS.md was created (the sweep must not touch the file)"

  # The [hygiene] task body names the flagged agent + the residue path.
  local body=""
  body="$(python3 "$REPO_ROOT/bridge-daemon-helpers.py" agent-doc-backfill-task-body \
    "$SMOKE_TMP_ROOT/t1.json" testhost)"
  smoke_assert_contains "$body" "Engine-mismatched docs" \
    "T1: task body missing the Engine-mismatched docs section"
  smoke_assert_contains "$body" "$agent" \
    "T1: task body did not name the flagged agent"
  smoke_assert_contains "$body" "roster_engine=claude" \
    "T1: task body did not surface the roster engine for the flagged agent"
  smoke_assert_contains "$body" "FLAG ONLY" \
    "T1: task body did not mark the section flag-only (must not imply auto-removal)"
}

# ===========================================================================
# T2 — a correct claude agent with only CLAUDE.md (no AGENTS.md) is NOT flagged
#      and the pass stays clean (no spurious [hygiene] task).
# ===========================================================================
test_clean_claude_no_agents_md_not_flagged() {
  setup_bridge_fixture
  local agent=t2claude
  write_roster "$agent" claude
  write_clean_claude_profile "$agent"
  local profile="$BRIDGE_AGENT_HOME_ROOT/$agent"

  local summary=""
  summary="$(run_backfill "$agent")"
  printf '%s' "$summary" >"$SMOKE_TMP_ROOT/t2.json"

  [[ ! -f "$profile/AGENTS.md" ]] \
    || smoke_fail "T2: clean claude agent unexpectedly has an AGENTS.md"
  smoke_assert_eq "0" "$(json_field "$SMOKE_TMP_ROOT/t2.json" engine_mismatch_docs_count)" \
    "T2: a clean claude agent was spuriously flagged as engine-mismatched"
  smoke_assert_eq "0" "$(non_clean_of "$SMOKE_TMP_ROOT/t2.json")" \
    "T2: a clean claude-skip pass was reported non-clean (spurious [hygiene] task)"
}

# ===========================================================================
# T3 — NEGATIVE CONTROL: a genuine codex-roster agent's own codex AGENTS.md is
#      NOT a mismatch and must never appear in engine_mismatch_docs.
# ===========================================================================
test_genuine_codex_agents_md_not_flagged() {
  setup_bridge_fixture
  local agent=t3codex
  write_roster "$agent" codex
  write_codex_profile_with_agents_md "$agent"

  local summary=""
  summary="$(run_backfill "$agent")"
  printf '%s' "$summary" >"$SMOKE_TMP_ROOT/t3.json"

  smoke_assert_eq "0" "$(json_field "$SMOKE_TMP_ROOT/t3.json" engine_mismatch_docs_count)" \
    "T3: a genuine codex agent's own AGENTS.md was flagged as engine-mismatched"
  smoke_assert_not_contains "$summary" "\"detected_contract\"" \
    "T3: a genuine codex agent produced an engine_mismatch_docs entry"
}

main() {
  smoke_run "T1 stale Codex-contract AGENTS.md on a claude agent is FLAGGED, not removed" \
    test_stale_codex_agents_md_is_flagged_not_removed
  smoke_run "T2 a clean claude agent with no AGENTS.md is not flagged (clean pass)" \
    test_clean_claude_no_agents_md_not_flagged
  smoke_run "T3 negative control: a genuine codex agent's own AGENTS.md is not a mismatch" \
    test_genuine_codex_agents_md_not_flagged
  smoke_log "PASS: $SMOKE_NAME"
}

main "$@"
